### ISSUE TITLE
Questions for evaluation

### ISSUE THREAD

**Issue by han0ah** [microsoft/dstc8-meta-dialog#4]
1. Can we use the prompt and the role sentences for our model? are these sentences also included in the real test data?

2. Are support dialogs given in the actual evaluation data the same task as the test dialog(within-task setting), or just the same domain? (cross-task setting).

3. Is the number of support dialogs per one test case also 128 in real test data?

4. During the development phase, could we assume that it is similar with the actual evaluation environment to test our model on MutiWoz dataset by measuring slot/intent accuracy of the predicted user response using Task1 baseline NLU?

5. Could you provide a more detailed description on the automatic measures(e.g. F1 score or accuracy of the slot/intent detection) that will be used for the actual test environment?

Thank you!

**Comment by aatkinson** [comment]
Hi! Thank you for your interest and questions, see the response below:

1. No, please don't use the prompt and role sentences in your model. We ask this since our evaluation dataset does not have all of these annotations.

2. Our evaluation dataset supports both the pure-task and cross-task cases, and we will evaluate the models in both scenarios.

3. Yes there will be 128 dialogues in the support set for each test case. This applies to both the pure-task and cross-task cases as well.

4. Yes, as described in the [task description](http://workshop.colips.org/dstc7/dstc8/DTSC8_multidomain_task_proposal.pdf) you can make this assumption.

5. We will be measuring BLEU 1-4 of the predicted response, and the F1 score of intent-slot matches computed with the NLU output on the predicted response, and the NLU output on the ground-truth response. You can consider these as a minimum; we are finalizing our evaluation methodology and will make an announcement if we decide to add more.

**Comment by shuaihuaiyi** [comment]
@aatkinson  Will there be any preprocessing (tokenization, lowercase or others) before you calculate these scores?
